config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'home/index'
  get 'services/index'
  get 'safety/index'
  get 'about/index'
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/safety_controller.rb
class SafetyController < ApplicationController
  def index
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.haml
%section#about.non-home
  .container
    %h1
      About Us
    .text-box
      %p
        honoring commitments to employees, clients and our industry guides our actions. Sleigo has grown because of the hard work and dedication of its employees. Together we aim to be recognized by our clients and peers as one of the most skilled construction companies in the business. A shared understanding of our Core Principles and Mission will help us carry out our historical commitments and continue to prosper.
      %h2
        Core Principals
      %ul
        %li
          We believe our employees are the Company's greatest asset, and support their efforts to learn new skills and achieve professional excellence.
        %li
          We will maintain a team-oriented workplace, with opportunities to do interesting and challenging work.
        %li
          We promise to follow high ethical standards in all of our business relationships.
        %li
          We will strive to recognize and meet the legitimate needs of our clients and employees.
        %li
          We are committed to providing superior services to all of our clients, and to deliver these services with courtesy and professionalism.
      %br
      %h2
        Our Mission
      %p
        Our shared mission is to deliver superior quality service to our clients by fostering an energetic, challenging, and comfortable work environment and be recognized by our clients and peers as a leader in our industry.

app/views/home/index.html.haml
%section#home
  .header-content
    = image_tag "header-text.svg", :class => "logo-img"
%section#main
  .main-text.container
    .text-block
      Sleigo Enterprises, LLC is a general contracting company specializing in powerline construction and maintenance, right of way clearing, land management, emergency restoration, and more. We posses exstensive electrical utility knowledge, operational expertise, electrical and telecommunications experience along with self performance capabilities covering all trades. Sleigo is a growing, veteran owned small business currently headquartered in Seven Points, TX with nationwide performance capacities.
  .contact-bar
    =mail_to "operations@sleigoenterprises.com" do
      Contact us for a quote today!
  .tri-block
    .card.services
      .card-cont
        .title Services
        .text We provide our customers with a multitude of storm restoration and other emergency utlity services.
        .read-more
          =link_to "read more", services_index_path
    .card.safety
      .card-cont
        .title Safety
        .text Our safety standards ensure that our customers' and employees' safety is always our top priority. &nbsp;
        .read-more
          =link_to "read more", safety_index_path
    .card.about
      .card-cont
        .title About Us
        .text Our core principals and comany mission will ensure that you are treated with the highest standards
        .read-more
          =link_to "read more", about_index_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ :name => "viewport", :content => "width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0" }
    %title Sleigo
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = favicon_link_tag "favicon.ico"
  %body
    = render "shared/nav_bar"
    = yield
    = render "shared/footer"

app/views/safety/index.html.haml
%section#safety.non-home
  .container
    %h1
      Safety
    .text-box
      %p
        We at Sleigo Enterprises strive to promote safe attitudes among our employees and take pride in providing customers and employees with a safe job site. Safety is always top priority. Every employee has the responsibility to prevent accident and injuries by observing established work rules, by following the directions of supervisors, by practicing the principles taught in safety training and by providing ideas on how safety efforts might be further enhanced.
      %p
        Our goal is for everyone to go home the way that they came to work. Contractors and employees performing work on job sites shall be required to comply with health, safety, and environmental regulations. Also, adopt safety practices equivalent to those applicable to Sleigo and/or Host Company.
      %h2
        Our Protocols
      %ul
        %li
          Full-Time Safety Coordinator
        %li
          OSHA Compliant Safety Programs
        %li
          Workers Compensation Insurance
        %li
          Frequent Safety Inspections
        %li
          Daily Tailgate Safety Meetings
        %li
          On-Going Safety Training
        %li
          First Aid and CPR Training
        %li
          Proper PPE and Quality Equipment

app/views/services/index.html.haml
%section#services.non-home
  .container
    %h1
      Services
    .text-box
      %h2
        Utilities
      %ul.utilities
        %li
          New construction on power lines from single phase to 3-phase to double circuit
        %li
          Reconduct work
        %li
          Primary underground
        %li
          Secondary services
        %li
          Conversions
        %li
          Maintenance
        %li
          Pole change outs
        %li
          Work on voltages that range from 7.2 kv to 34.5 kv
        %li
          Work on transmissions ranging from 69kv to138kv.
        %li
          New construction
        %li
          Rebuilds
        %li
          Conversions
        %li
          Maintenance
        %li
          Troubleshoots and call outs
        %li
          Pole change outs
      %ul.utilities
        %li
          Street Light Install/Repair
        %li
          New Construction
        %li
          Reconduct
        %li
          Trouble Calls
        %li
          Secondary Reconduct
        %li
          Storm Restoration
        %li
          Pole Change Outs
        %li
          Installations of Transformers and Change Outs
        %li
          Troubleshooting
        %li
          System Upgrades
        %li
          Maintenance
        %li
          Re-insulations
        %li
          Installation of Capacitors and Reclosers Equipment
        %li
          Voltage Conversions
        %li
          Engineering
    .text-box.storm
      .pic
        = image_tag "storm-restoration.jpeg"
      .text
        %h2
          Storm Restoration
        %p
          Sleigo’s emergency restoration crews are typically one of the first to respond and last to leave. The company is committed to restore power in a timely and professional manner to those in need. Some noteable Emergency Response assignments are hurricanes Harvey, Irma, and Maria along with multiple ice storms throughout the U.S.
        %ul
          %li
            Rapid Response
          %li
            Customer Centered Service
          %li
            Experienced Team
          %li
            Quality Fleet
          %li
            FEMA rapid response contract with Gulf Coast
    .text-box.equipment
      .text
        %h2
          Equipment
        %ul
          %li
            Service Trucks
          %li
            Buckets that range from 38’-60’
          %li
            Digger Derricks that range from 45-65’
          %li
            Dozers
          %li
            Mini Excavators
          %li
            Skid-Steers with pole setting attachments and auger attachments
          %li
            Trenching Equipment
          %li
            Rope Rigs
          %li
            Tensioners
          %li
            Material Trailers
          %li
            Pole Trailers
          %li
            ATV’s
      .pic
        = image_tag "equipment.jpeg"

app/views/shared/_footer.html.haml
%section#footer
  .container
    .footer-container
      .footer-img-box
        = image_tag "navoba.png", :class => "footer-img"
      .footer-img-box
        = image_tag "fed.png", :class => "footer-img"
      .footer-img-box
        = image_tag "lineman.png", :class => "footer-img"
      .footer-img-box
        = image_tag "ariba.png", :class => "footer-img"
      .footer-text-box
        %ul
          %li
            %h3
              SLEIGO ENTERPRISES
          %li
            3070 ARNOLD HILLS ROAD
          %li
            SEVEN POINTS, TX 75143
          %li
            (903) 603-4085

app/views/shared/_nav_bar.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to image_tag('/assets/logo-text-color.png'), root_path, class: 'navbar-brand'

    .collapse.navbar-collapse#bs-example-navbar-collapse-1
      %ul.nav.navbar-nav

        / Sample links
        %li= link_to 'Home', '/'
        %li= link_to 'Services', services_index_path
        %li= link_to 'Safety', safety_index_path
        %li= link_to 'About', about_index_path
        //%li= link_to 'Contact', '#'